name: Build


on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build with Maven
        run: ./mvnw package --batch-mode --no-transfer-progress

      - name: Archive JAR
        uses: actions/upload-artifact@v3
        with:
          name: app.jar
          path: |
            target/app.jar
  # tag::container-build[]
  package:
    name: Build Container Image
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
    - uses: actions/checkout@v3

    - name: Download JAR
      uses: actions/download-artifact@v3
      with:
        name: app.jar
    - run: |
        mkdir target
        mv app.jar target/

    - name: Buildah Action
      uses: redhat-actions/buildah-build@v2
      with:
        image: buildah-app
        tags: v1 ${{ github.sha }}
        containerfiles: |
          ./Dockerfile
   # end::container-build[]
